# Generated by Django 4.2.9 on 2024-02-21 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speech2text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
