# Generated by Django 4.2.9 on 2024-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech2text', '0002_alter_attempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='audio_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Audio code'),
        ),
    ]
