# Generated by Django 4.2.9 on 2024-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech2text', '0003_attempt_audio_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Audio text'),
        ),
    ]
