# Generated by Django 4.2.9 on 2024-03-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_use',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Kunlik foydalanish imkoniyati'),
        ),
    ]
